source 'https://rubygems.org'

group :development, :test do
  gem 'jekyll', '~> 3.7.0'
  gem 'jekyll-redirect-from', '~> 0.13.0'
  gem 'jekyll-sitemap', '~> 1.1.1'
  gem 'jekyll-toc', '~> 0.5.1'
  gem "nokogiri", ">= 1.8.5"
end
